# OrbStack configuration for VCF Analysis Agent
version: '3.8'

services:
  vcf-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vcf_agent_dev
    volumes:
      - ./:/app
    ports:
      - "8000:8000"  # Change if your app uses a different port
    environment:
      - ORBSTACK_SERVER=192.168.0.225
    networks:
      - orbstack-net

networks:
  orbstack-net:
    external: true 